import React, { useState } from 'react';
import { ChevronDown, HelpCircle, Phone, ArrowRight } from 'lucide-react';

export const FAQSection: React.FC = () => {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How long does solar panel installation take in Maharashtra?',
      a: 'The installation time depends on the system size. For residential installations (1–10 kW), it typically takes 2–4 days. For commercial installations (10–100 kW), it takes 1–2 weeks. This includes mounting structures, installing Tier-1 panels, inverters, wiring, and safety earthing. Invisible Energy handles the entire timeline swiftly.',
    },
    {
      q: 'What government subsidies are available in Maharashtra under PM Surya Ghar?',
      a: 'Under the PM Surya Ghar Muft Bijli Yojana, residential households receive direct subsidy: ₹30,000 per kW for up to 2kW, and ₹18,000 for the 3rd kW—giving up to ₹78,000 in direct bank transfers (DBT). Commercial and industrial users benefit from accelerated depreciation (40%) and GST input tax credits. Invisible Energy assists with all documentation and DISCOM portal filings.',
    },
    {
      q: 'What is the cost of solar panel installation in Maharashtra?',
      a: 'On average, a residential rooftop solar system costs ₹50,000–₹60,000 per kW before subsidies. A typical 3kW home system costs around ₹1.5–1.8 lakhs, which comes down to ₹90,000–1.1 lakhs after PM Surya Ghar subsidies. Commercial systems benefit from economies of scale. We offer customized quotes with clear ROI calculations.',
    },
    {
      q: 'What is the payback period for solar panels in Maharashtra?',
      a: "With Maharashtra's high solar irradiation (averaging 5–6 peak sunlight hours daily) and prevailing MSEDCL electricity tariffs, the typical payback period is 4–6 years for residential homes and 3–5 years for commercial establishments. After subsidy, payback can be as short as 3–4 years. With a 25+ year lifespan, you enjoy 20+ years of virtually free electricity.",
    },
    {
      q: 'Do solar panels work during cloudy or monsoon days?',
      a: 'Yes! Modern Tier-1 Mono PERC and TOPCon solar panels operate on light radiation rather than heat. On cloudy or rainy days, panels continue producing 25% to 40% of their standard capacity from diffuse sunlight. Across the full 12 months, Maharashtra provides more than 300 days of strong sun, easily balancing your annual net metering credits.',
    },
    {
      q: 'How does net metering work with MSEDCL (Mahavitaran)?',
      a: 'Net metering replaces your single-direction electric meter with a bi-directional meter. During bright daytime hours, excess electricity generated by your solar system flows into the MSEDCL grid, earning kilowatt-hour credits. At night, your home draws power from the grid against these credits. Your monthly bill is only for the net difference, reducing costs by up to 80%.',
    },
  ];

  return (
    <section id="faq" className="relative py-16 sm:py-24 px-4 sm:px-6 md:px-12 lg:px-16 bg-slate-50 text-slate-900 border-t border-slate-200">
      <div className="max-w-4xl mx-auto relative z-10 space-y-12">

        {/* Section Header */}
        <div className="text-center space-y-3 sm:space-y-4">
          <span className="text-xs font-bold uppercase tracking-wider text-emerald-800 bg-emerald-100/70 px-3.5 py-1 rounded-full border border-emerald-200 inline-flex items-center gap-1.5">
            <HelpCircle className="w-3.5 h-3.5 text-emerald-700" />
            FREQUENTLY ASKED QUESTIONS
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold tracking-tight text-slate-900 leading-tight">
            Solar Installation <span className="font-editorial-italic font-normal text-emerald-800">FAQs</span>
          </h2>
          <p className="text-slate-600 text-sm sm:text-base max-w-xl mx-auto leading-relaxed">
            Everything you need to know about rooftop solar, government subsidies, net metering, and installation in Sangli &amp; Maharashtra.
          </p>
        </div>

        {/* Accordion List */}
        <div className="space-y-3.5">
          {faqs.map((faq, idx) => {
            const isOpen = openIdx === idx;
            return (
              <div
                key={idx}
                className="bg-white rounded-2xl border border-slate-200 shadow-2xs overflow-hidden transition-all duration-200"
              >
                <button
                  type="button"
                  onClick={() => setOpenIdx(isOpen ? null : idx)}
                  className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 focus:outline-none cursor-pointer"
                >
                  <span className="text-base sm:text-lg font-bold text-slate-900 tracking-tight leading-snug">
                    {faq.q}
                  </span>
                  <div
                    className={`w-8 h-8 rounded-full border flex items-center justify-center shrink-0 transition-transform duration-300 ${
                      isOpen
                        ? 'rotate-180 bg-[#C6F500] text-black border-lime-500 shadow-xs'
                        : 'bg-slate-100 text-slate-600 border-slate-200'
                    }`}
                  >
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-5 sm:px-6 pb-6 pt-1 text-sm sm:text-base text-slate-600 leading-relaxed border-t border-slate-100 animate-in fade-in duration-200">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Have More Questions Prompt */}
        <div className="bg-emerald-50 border border-emerald-200/80 rounded-2xl p-5 sm:p-6 text-center flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="text-center sm:text-left">
            <h4 className="text-sm sm:text-base font-bold text-slate-900">
              Have any other questions about going solar?
            </h4>
            <p className="text-xs sm:text-sm text-slate-600 mt-0.5">
              Speak directly with an Invisible Energy solar engineer in Sangli.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="tel:+918888208099"
              className="inline-flex items-center gap-2 bg-white hover:bg-slate-50 text-slate-900 font-bold text-xs sm:text-sm px-4 py-2.5 rounded-full border border-slate-200 shadow-xs transition-colors"
            >
              <Phone className="w-3.5 h-3.5 text-emerald-700" />
              <span>+91 8888208099</span>
            </a>
            <a
              href="#contact"
              className="inline-flex items-center gap-1.5 bg-[#C6F500] hover:bg-[#b8e500] text-black font-bold text-xs sm:text-sm px-4 py-2.5 rounded-full shadow-xs transition-colors"
            >
              <span>Ask a Question</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </a>
          </div>
        </div>

      </div>
    </section>
  );
};
